name: Hello ci
on:
  push:
    branches: 
      - main
      
jobs:
  greeting:
    name: Greeting
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello, CI"
  setup_minikube:
    name: Set Up Minikube
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Up ssh key
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/minikube
          touch ~/.ssh/known_hosts
          echo "${{ secrets.MINIKUBE_SSH_KEY }}" > ~/.ssh/minikube
          echo "${{ secrets.MINIKUBE_SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/minikube
          
      - name: Set up minikube connection
        run: |
          mkdir ~/k8s.raezhov.fun
          cd ~/k8s.raezhov.fun
          scp -i ~/.ssh/minikube admin@k8s.raezhov.fun:/home/admin/.minikube/ca.crt .
          scp -i ~/.ssh/minikube admin@k8s.raezhov.fun:/home/admin/.minikube/profiles/minikube/client.crt .
          scp -i ~/.ssh/minikube admin@k8s.raezhov.fun:/home/admin/.minikube/profiles/minikube/client.key .
          ls -a
          
      - name: Download kubectl
        run: |
          mkdir ~/kubectl
          cd ~/kubectl
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Create tunel
        run: ssh -N -p 22 admin@k8s.raezhov.fun -i ~/.ssh/minikube -L 18443:192.168.49.2:8443 &
        
      - name: Check nodes
        run: |
          kubectl get nodes
